Adding build strategy in Mac platform.
dydtjr1128/WordCounter pull request #4
Opened 2020-03-14 10:24 UTC by ken1336

Adding build strategy in Mac platform.

2020-03-14 10:26 UTC, ken1336 commented
build폴더 제외하는거 까먹음ㅠ

2020-03-14 10:45 UTC, dydtjr1128 requested changes
Need to remove unnecessary comment!

2020-03-14 10:45 UTC, dydtjr1128 commented on FindWords/FindWords.cpp
> +	std::cout<<"Min contribute. Happy hack!"<<std::endl;
이건 대체 왜 넣은건가요 지워주세요.

2020-04-21 02:38 UTC, dydtjr1128 requested changes

2020-04-21 02:38 UTC, dydtjr1128 commented on FindWords/FileWriter.h
> +                std::ofstream outStream;
`outStream_;`

2020-04-21 02:38 UTC, dydtjr1128 commented on FindWords/FileWriter.h
> +                void writeTextInFile();
`W`riteTextInFile();

2020-04-21 02:38 UTC, dydtjr1128 commented on FindWords/FileWriter.h
> +                int writeTest(std::string text);
UpperCase

2020-04-21 02:38 UTC, dydtjr1128 commented on FindWords/ThreadPool.cpp
> +			throw std::runtime_error("ThreadPool ��� ������");
Character Encoding

2026-07-17 08:10 UTC, dydtjr1128 requested changes
.

2026-07-25 16:21 UTC, closed without merging